DATABASE_URL: "jdbc:postgresql://auth-db:5432/auth_service"
POSTGRES_USERNAME: vou
POSTGRES_PASSWORD: vouadmin123
KAFKA_BOOTSTRAP_SERVERS: kafka:9092
SERVER_PORT: 8001
JWT_SIGNER_KEY: "REPLACETHISWITHSOMETHINGELSEPLEASE"
JWT_VALID_DURATION: 3600
JWT_REFRESHABLE_DURATION: 36000