DATABASE_URL: "jdbc:postgresql://localhost:5431/auth_service"
POSTGRES_USERNAME: vou
POSTGRES_PASSWORD: vouadmin123
KAFKA_BOOTSTRAP_SERVERS: localhost:9094
SERVER_PORT: 8001
JWT_SIGNER_KEY: "REPLACETHISWITHSOMETHINGELSEPLEASE"
JWT_VALID_DURATION: 3600
JWT_REFRESHABLE_DURATION: 36000