DATABASE_URL: ${SPRING_DATASOURCE_URL}
POSTGRES_USERNAME: ${POSTGRES_USER}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
SERVER_PORT: 8001
JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
JWT_VALID_DURATION: ${JWT_VALID_DURATION}
JWT_REFRESHABLE_DURATION: ${JWT_REFRESHABLE_DURATION}