apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    app: user-service
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_service
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092