apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-db
spec:
  replicas: 1
  serviceName: event-db
  selector:
    matchLabels:
      app: event-db
  template:
    metadata:
      labels:
        app: event-db
    spec:
      containers:
      - name: event-db
        image: postgres:latest
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: event-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: event-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: event-db-secret
              key: POSTGRES_DB
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: event-storage
          mountPath: /var/lib/postgresql/data/db
      volumes:
      - name: event-storage
        persistentVolumeClaim:
          claimName: event-pvc
