spring:
  active:
    profiles: ${ACTIVE_PROFILE:local}
  application:
    name: EventService
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT}