spring:
  application:
    name: EventService
  datasource:
    url: jdbc:postgresql://localhost:5433/event_service
    username: vou
    password: vouadmin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    producer:
      bootstrap-servers: localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
server:
  port: 8003
