apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notification-db
spec:
  replicas: 1
  serviceName: notification-db
  selector:
    matchLabels:
      app: notification-db
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
      - name: notification-db
        image: bitnami/mongodb:7.0.11
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        volumeMounts:
        - name: notification-storage
          mountPath: /data/db
      volumes:
      - name: notification-storage
        persistentVolumeClaim:
          claimName: notification-pvc
