server.port=8002
spring.application.name=UserVOAService
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=vou
spring.datasource.password=vouadmin123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update