server:
  port:
    8002
spring:
  application:
    name: UserVOAService
  datasource:
    url: jdbc:postgresql://user-db:5432/user_service
    username: vou
    password: vouadmin123
  jpa:
    hibernate:
      ddl-auto: update
