

services:
  app:
    build: .
    ports:
      - "8001:8001"
    networks:
      - auth-network
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5431:5432"
    networks:
      - auth-network
    environment:
      POSTGRES_USER: vou
      POSTGRES_PASSWORD: vouadmin123
      POSTGRES_DB: auth_service
    volumes:
      - auth-data:/var/lib/postgresql/data

networks:
  auth-network:
    driver: bridge

volumes:
  auth-data: