

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - bridged-network

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - bridged-network
    environment:
      POSTGRES_USER: vou
      POSTGRES_PASSWORD: vouadmin123
      POSTGRES_DB: auth_service
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin: # For dashboard
    depends_on:
      - db
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    networks:
      - bridged-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vou.com
      PGADMIN_DEFAULT_PASSWORD: voudadmin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  bridged-network:
    driver: bridge

volumes:
  pgadmin-data:
  db-data: