apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  ports:
  - port: 8001
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30300
  selector:
    app: auth-api