apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-config
  labels:
    app: event-service
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://event-db:5432/event_service
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092