apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-api
  labels:
    app: event-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-api
  template:
    metadata:
      labels:
        app: event-api
    spec:
      containers:
      - name: event-api
        image: vou-backend-event-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
        resources:
          limits:
            memory: "1Gi"
            cpu: "200m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: event-service-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: event-service-config
              key: SPRING_DATASOURCE_URL
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: event-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: event-db-secret
              key: POSTGRES_PASSWORD