server:
  port: 8005
  servlet:
    context-path: /notification
spring:
  application:
    name: NotficationService
  data:
    mongodb:
      uri: mongodb://root:root@localhost:5435/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

firebase:
  firebaseCredentialFile: firebase-service-account.json