server:
  port: ${SERVER_PORT}
spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: NotficationService
  data:
    mongodb:
      uri: ${MONGO_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

firebase:
  firebaseCredentialFile: firebase-service-account.json