apiVersion: v1
kind: Service
metadata:
  name: mc-service
spec:
  selector:
    app: mc-api
  ports:
  - port: 8006
    targetPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: mc-service-socket
spec:
  selector:
    app: mc-api
  ports:
  - port: 8100
    targetPort: 8100