name: 'Build docker compose file and push to Artifact Registry'

on:
  push:
    branches: [ "deploy" ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}


jobs:
  build:
  
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create shorter commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      # Build the Docker images
      - name: Build Docker images
        run: |
          version=${{ steps.vars.outputs.sha_short }}
          docker compose --profile API -f ./docker-compose-prod.yaml build -q

      # Build the Docker images
      - name: Build Docker images
        run: |
          version=${{ steps.vars.outputs.sha_short }}
          docker compose --profile API -f ./docker-compose-prod.yaml build -q

      # Authenticate to Google Cloud
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      # Authenticate to the Docker registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'


      # Push the Docker images to the Artifact Registry
      - name: Push Docker images
        run: |
          version=${{ steps.vars.outputs.sha_short }}
          docker compose --profile API -f ./docker-compose-prod.yaml push -q